name: Quality

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python-quality:
    uses: jesseray718/.github/.github/workflows/python-quality.yml@main
    with:
      python-version: "3.12"
      compile-path: "."
      test-command: "python -m unittest discover -v"
